/**
 * PII Shield — per-tool privacy policy registry.
 *
 * When the LLM emits a tool call against an anonymized session, the
 * backend must decide what to do with the placeholders inside the tool
 * arguments and what to do with the values that come back:
 *
 *  - `deanonymize`  — replace placeholders with original PII before
 *                     invoking the tool (safe for *internal* tools that
 *                     never leak data outside the trust boundary).
 *  - `passthrough`  — leave placeholders untouched in the request, and
 *                     re-anonymize any placeholder-free PII detected in
 *                     the response (default safe choice for external
 *                     services).
 *  - `block`        — refuse to execute the tool in strict mode. The
 *                     tool result becomes a controlled error message
 *                     that the LLM sees instead of the real result.
 *
 * See plan §11 Gap #10 (R1) for the rationale. This registry is the
 * single source of truth — `chatTools.ts:runToolCalls` consults it
 * before invoking any tool when a chat session has PII Shield active.
 */

/**
 * Policy values supported per tool.
 *
 * The "default" symbol is reserved for explicit fallback lookups; do not
 * use it in the registry tables themselves.
 */
export type ToolPiiPolicy = "deanonymize" | "passthrough" | "block";

/**
 * Internal tools (defined by `chatTools.ts`'s `TOOL_DEFINITIONS`).
 * These run inside our backend trust boundary, so receiving real PII is
 * safe — and in fact necessary, otherwise document lookups would match
 * the placeholder string instead of the real customer name.
 *
 * Keep this list in sync with the tool registrations in
 * `backend/src/lib/chatTools.ts`. Missing entries fall through to
 * `getToolPiiPolicy`'s `passthrough` default.
 */
export const TOOL_PII_POLICIES: Readonly<Record<string, ToolPiiPolicy>> = {
    // Document IO — internal, safe to de-anonymize.
    readDocumentContent: "deanonymize",
    findInDocument: "deanonymize",
    createDocument: "deanonymize",
    editDocument: "deanonymize",
    replicateDocument: "deanonymize",
    searchDocuments: "deanonymize",

    // Workflow runs touch the same documents as the user, treat as internal.
    runWorkflow: "deanonymize",

    // Web search runs against an *external* service. We want degraded
    // results over leaking PII, so always pass placeholders through.
    // The mike-shield will re-redact PII that comes back in snippets.
    webSearch: "passthrough",
};

/**
 * MCP tools live behind the `mcp__<slug>__<toolName>` naming convention
 * (see `backend/src/lib/mcp/servers.ts`, `TOOL_PREFIX = "mcp__"`).
 * Policy is decided per *server slug*, not per individual MCP tool, so
 * the table stays small even as third-party servers add tools.
 *
 * Defaults are conservative: any MCP server not explicitly listed is
 * `passthrough` (placeholders kept) because we can't a priori trust an
 * arbitrary external service to handle PII safely.
 */
export const MCP_SERVER_PII_POLICIES: Readonly<Record<string, ToolPiiPolicy>> = {
    // Email — classic PII sink. Strict mode blocks it; standard treats
    // placeholders as opaque (passthrough). See plan §11 Gap #10.
    gmail: "block",

    // Knowledge / search / dev tools — passthrough is safe because the
    // user can always copy real values manually if they want them in
    // the search query, but we will not send them automatically.
    atlassian: "passthrough",
    context7: "passthrough",
    neo4j: "passthrough",
    pinecone: "passthrough",
    tavily: "passthrough",
    github: "passthrough",
    firebase: "passthrough",
    "cloud-sql-postgresql": "passthrough",
    "cloud-sql-postgresql-admin": "passthrough",
    cloudrun: "passthrough",
    "ydc-server": "passthrough",
};

/**
 * Wildcard fallback for any MCP server not listed above.
 *
 * `passthrough` — keep PII out of unknown third-party services by default.
 * Override per-server above when a deeper integration is desired.
 */
export const MCP_DEFAULT_POLICY: ToolPiiPolicy = "passthrough";

const TOOL_PREFIX = "mcp__";

/**
 * True for tools generated by the MCP layer (any name starting with
 * `mcp__`). Mirrors the matching test in `chatTools.ts:1872`.
 */
export function isMcpTool(toolName: string): boolean {
    return toolName.startsWith(TOOL_PREFIX);
}

/**
 * Best-effort extraction of the MCP server slug from a prefixed tool
 * name. Format produced by `prefixedToolName(slug, name)` in
 * `backend/src/lib/mcp/servers.ts`:
 *
 *   `mcp__<slug>__<toolName>`
 *
 * Where `<slug>` itself MAY contain underscores (e.g. `cloud-sql-postgresql`
 * is fine because slugs use hyphens, but `user-context7` -> slug is just
 * `user-context7`). The split is on the LAST `__` pair, taking the bit
 * between the leading `mcp__` and the next `__` as the slug.
 *
 * For names that were truncated through the SHA256-fallback path in
 * `servers.ts:127`, this best-effort parse may return null — callers
 * should prefer passing the resolved slug explicitly when they have it
 * (see `getMcpServerPolicy`).
 *
 * @returns the slug or null when the name is not a well-formed MCP tool.
 */
export function extractMcpSlug(toolName: string): string | null {
    if (!isMcpTool(toolName)) return null;
    const tail = toolName.slice(TOOL_PREFIX.length);
    const nextSep = tail.indexOf("__");
    if (nextSep <= 0) return null;
    return tail.slice(0, nextSep);
}

/**
 * Lookup the MCP policy for a given slug, falling back to the wildcard
 * default when the slug is unknown.
 */
export function getMcpServerPolicy(slug: string): ToolPiiPolicy {
    return MCP_SERVER_PII_POLICIES[slug] ?? MCP_DEFAULT_POLICY;
}

/**
 * Resolve the PII policy for an arbitrary tool name.
 *
 *  - Internal tools (`readDocumentContent`, `webSearch`, …): exact match
 *    in `TOOL_PII_POLICIES`.
 *  - MCP tools (`mcp__<slug>__<name>`): look up the slug in
 *    `MCP_SERVER_PII_POLICIES`; fallback to `MCP_DEFAULT_POLICY`.
 *  - Unknown tool name: `passthrough` (safe default — never leak PII).
 *
 * @param toolName the function name as the LLM emitted it.
 * @param slugOverride when the caller has the resolved server slug
 *   already (e.g. via `findMcpServerForTool`), pass it to avoid the
 *   best-effort string parse and to handle hash-truncated tool names.
 */
export function getToolPiiPolicy(
    toolName: string,
    slugOverride?: string,
): ToolPiiPolicy {
    if (Object.prototype.hasOwnProperty.call(TOOL_PII_POLICIES, toolName)) {
        return TOOL_PII_POLICIES[toolName];
    }
    if (isMcpTool(toolName)) {
        const slug = slugOverride ?? extractMcpSlug(toolName);
        if (slug) return getMcpServerPolicy(slug);
        return MCP_DEFAULT_POLICY;
    }
    return "passthrough";
}

/**
 * Strict-mode gate. Returns true when the policy says we MUST refuse to
 * execute this tool in strict mode. Used by `runToolCalls` to produce a
 * deterministic error response instead of running the tool.
 *
 * In non-strict modes (`standard`, `strict_legal`) `block` policies
 * still execute the tool but with placeholders intact (effectively
 * `passthrough` semantics) — only `strict` honours the block.
 */
export function shouldBlockInStrict(toolName: string, slugOverride?: string): boolean {
    return getToolPiiPolicy(toolName, slugOverride) === "block";
}
